name: Request to add your event to the Bioconductor event calendar
description: File an event calendar request
title: "[Event]: REPLACE ME WITH YOUR EVENT NAME"
labels: [event, calendar]
assignees:
  - kozo2

body:
  - type: markdown
    attributes:
      value: |
        Submit this form to list your event on the Bioconductor event calendar.
        Please review the following guidelines before submitting:

          1. Events must have a Bioconductor focus to be included in the Bioconductor Events Calendar.
          2. Events relevant to the Bioconductor community but without a direct focus on Bioconductor tools will be listed in the Other Relevant Events Calendar.
          3. The event organizer should confirm they have read the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).

        Thank you for your submission!

  - type: dropdown
    id: event-category
    attributes:
      label: Event Category
      description: Select the category that best describes your event.
      options:
        - Bioconductor Event (direct focus on Bioconductor tools/packages)
        - Other Relevant Event (relevant to the community but not directly focused on Bioconductor)
    validations:
      required: true

  - type: textarea
    id: event-type
    attributes:
      label: Type
      description: Specify the type of your event (e.g., workshop, hack-a-thon, meetup, lecture, etc.)
      placeholder: Tell us your event type!
    validations:
      required: true

  - type: textarea
    id: event-description
    attributes:
      label: Description
      description: Provide a brief description of your event.
      placeholder: Tell us your event description!
    validations:
      required: true

  - type: textarea
    id: bioconductor-relevance
    attributes:
      label: How does this event relate to Bioconductor?
      description: |
        Clearly describe how this event is related to Bioconductor, especially if you're submitting it as a Bioconductor Event. 
        For Other Relevant Events, explain the relevance to the community.
      placeholder: Describe the relevance of your event to Bioconductor.
    validations:
      required: true

  - type: textarea
    id: event-location
    attributes:
      label: Where is your event located?
      description: Provide the location and time zone of your event, and specify if it is virtual.
      placeholder: Tell us your event location and time-zone + if it is virtual or not.
    validations:
      required: true

  - type: textarea
    id: event-website
    attributes:
      label: Website
      description: Provide the website for your event.
      placeholder: https://eventwebsite.com
    validations:
      required: true

  - type: dropdown
    id: repeating-or-oneoff
    attributes:
      label: Repeating or one-off event?
      description: Select whether the event is repeating or a one-off occurrence.
      options:
        - Repeating
        - One-off
    validations:
      required: true

  - type: textarea
    id: repeating-details
    attributes:
      label: Repeating Event Schedule (if applicable)
      description: If your event is repeating, please specify the schedule details (e.g., "Repeats every Monday at 3:00 PM", "Monthly on the 15th", etc.).
      placeholder: Provide details about the event's repeating schedule.
    validations:
      required: false

  - type: textarea
    id: repeating-time
    attributes:
      label: Repeating Event Time (if applicable)
      description: Specify the time for each occurrence of the repeating event.
      placeholder: e.g., 3:00 PM - 4:00 PM
    validations:
      required: false

  - type: textarea
    id: oneoff-date-time
    attributes:
      label: One-off Event Date and Time (if applicable)
      description: If your event is a one-off, specify the date and time.
      placeholder: e.g., April 15th, 3:00 PM - 4:00 PM
    validations:
      required: false

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: Provide your email address if you're comfortable sharing it. We'll use it to contact you if needed.
      placeholder: ex. email@example.com      

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following before submitting.
      options:
        - label: This event is relevant to the Bioconductor community.
          required: true
        - label: The event organizer has read and confirmed the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event has a Code of Conduct (CoC) derived from the partner organization or the [Bioconductor Code of Conduct](http://bioconductor.org/about/code-of-conduct/).
          required: true
        - label: The event organizer will provide a summary of the CoC to participants.
          required: true
